### ISSUE TITLE
RuntimeError: invalid hash value 

### ISSUE THREAD

**Issue by lszp** [hobincar/pytorch-video-feature-extractor#5]
Hello, thanks for your codes.
I installed python packages specified in requirement.txt, but when I run inception_v4.sh script, I encounter following problem:
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    model = getattr(nets, args.model)(pretrained=True) # return function(pretrained=True)
  File "/home/zhangpan/videoCaption/pytorch-video-feature-extractor/nets/inceptionv4.py", line 321, in inceptionv4
    model.load_state_dict(model_zoo.load_url(settings['url']))
  File "/home/zhangpan/anaconda3/lib/python3.7/site-packages/torch/utils/model_zoo.py", line 66, in load_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/zhangpan/anaconda3/lib/python3.7/site-packages/torch/utils/model_zoo.py", line 106, in _download_url_to_file
    .format(hash_prefix, digest))
RuntimeError: invalid hash value (expected "8e4777a0", got "43edeb8834bcecdcc860d3ed2d4b65843ef75c3ad2202917dc5c3b1ca6373392")
Could you tell me what may result in it ?

**Comment by hobincar** [comment]
Hi,

I tried to reproduce your error by starting again with re-cloning, but it was just fine in my case. Can you check that you are in the same environment with me (e.g., Python 3.6.8, etc.)

**Comment by lszp** [comment]
Thanks for your reply. 
The problem is caused by network problems when downloading pre-trained model.
Now it's ok.

**Comment by hobincar** [comment]
Thank you for the feedback. I really appreciate it. Thanks!
